/* Direção visual: Fluxo Circular — inclusive em páginas utilitárias, com marcadores de percurso e rodapé institucional. */
import Home from "./pages/Home";
import { Route, Switch } from "wouter";

function Privacy() {
  return <div className="utility-page"><header className="site-header"><div className="nav-wrap"><a href="/"><div className="brand"><img src="/assets/maxoleo-mark.png" alt="" aria-hidden="true" /><span><strong>MAXÓLEO</strong><small>SOLUÇÕES AMBIENTAIS</small></span></div></a><a className="button button--small button--green" href="/">Voltar ao site <span>↗</span></a></div></header><main className="utility-main"><div className="utility-route"><span className="section-index">04</span><span className="vertical-rule" /><span className="aside-label">ROTA DE<br />TRANSPARÊNCIA</span></div><p className="kicker"><span className="kicker-dot" />DOCUMENTAÇÃO E PRIVACIDADE</p><h1>Política de<br /><em>privacidade.</em></h1><p className="utility-lede">A MAXÓLEO utiliza os dados enviados voluntariamente pelo WhatsApp ou pelo Google Forms exclusivamente para responder solicitações, avaliar a coleta e organizar o atendimento.</p><div className="utility-board"><div><strong>01 — USO DAS INFORMAÇÕES</strong><p>Não vendemos dados pessoais nem usamos as informações para finalidades incompatíveis com o contato solicitado. Para dúvidas sobre privacidade, escreva para maxoleos.coleta@gmail.com.</p></div><div><strong>02 — FORMULÁRIO EXTERNO</strong><p>O Google Forms é operado pelo Google e pode aplicar suas próprias políticas e tecnologias de tratamento de dados. Recomendamos consultar as informações apresentadas na própria plataforma antes de enviar o formulário.</p></div></div></main><footer className="site-footer"><div className="container footer-bottom"><p>MAXÓLEO é uma iniciativa da MR Desentupidora Ltda. · CNPJ 21.587.809/0001-31</p><p>Contato: maxoleos.coleta@gmail.com</p></div></footer></div>;
}
function NotFound() { return <main className="utility-main"><p className="kicker"><span className="kicker-dot" />ROTA NÃO ENCONTRADA</p><h1>Este caminho<br /><em>não existe.</em></h1><p className="utility-lede">Volte para a página inicial da MAXÓLEO e encontre a rota correta.</p><a className="button button--green" href="/">Voltar ao início →</a></main>; }
export default function App() { return <Switch><Route path="/" component={Home} /><Route path="/privacidade" component={Privacy} /><Route path="/404" component={NotFound} /><Route component={NotFound} /></Switch>; }
